name: Remote Update and Restart

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into AWS and Update
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          # This secret should contain your PRIVATE SSH key
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          script: |
            if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              echo "Deploying to Production..."
              cd ~/inkbattle-backend
              git pull origin main
              npm install --production
              pm2 restart inkbattle-backend
            elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
              echo "Deploying to Staging..."
              cd ~/inkbattle-backend_staging
              git pull origin staging
              npm install
              pm2 restart inkbattle-staging
            fi
